services:
  scrapper:
    container_name: scrapper
    build:
      context: ./scrapper
      dockerfile: Dockerfile
    ports:
      - "8088:8000"
    volumes:
      - ./scrapper/app:/app/app
    depends_on:
      - playwright
    environment:
      PLAYWRIGHT_WS_URL: ws://playwright:3000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  playwright:
    image: mcr.microsoft.com/playwright:v1.51.0-noble
    container_name: playwright
    init: true
    working_dir: /home/pwuser
    user: pwuser
    command: >
      /bin/sh -c "npx -y playwright@1.51.0 run-server --port 3000 --host 0.0.0.0"
